version: '3.8'
services:
  db:
    image: mongo:6
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  backend:
    build:
      context: ./backend
    env_file:
      - ./backend/.env.backend
    depends_on:
      - db
    ports:
      - "4000:4000"
    volumes:
      - ./backend:/app

  frontend:
    build:
      context: ./frontend
    env_file:
      - ./frontend/.env.frontend
    depends_on:
      - backend
    ports:
      - "3000:80"

  nginx:
    image: nginx:alpine
    volumes:
      - ./nginx/frontend.conf:/etc/nginx/conf.d/default.conf:ro
      - ./frontend/build:/usr/share/nginx/html:ro
    ports:
      - "80:80"
    depends_on:
      - frontend
      - backend

volumes:
  mongo_data:
